version: '3.1'

services:

  db:
    image: library/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ads
    ports:
      - 5432:5432

  minio:
    image: quay.io/minio/minio:RELEASE.2022-03-22T02-05-10Z
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9100:9100"
    command: server --console-address ":9100" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
volumes:
  minio_data: